// k6 script for load testing get_emergency_card RPC
import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// Load list of UUIDs from a file (generated by seed script)
const uuids = new SharedArray('card ids', function () {
  // The file should contain one UUID per line
  return open('loadtest/card_ids.txt').split('\n').filter(id => id.length > 0);
});

export const options = {
  stages: [
    { duration: '30s', target: Number(__ENV.CONCURRENCY) || 100 }, // ramp-up
    { duration: '2m', target: Number(__ENV.CONCURRENCY) || 100 }, // steady load
    { duration: '30s', target: 0 }, // ramp-down
  ],
  thresholds: {
    http_req_duration: ['p(50)<500', 'p(95)<1500'], // example SLOs
    errors: ['rate<0.01'],
  },
};

export default function () {
  const id = uuids[Math.floor(Math.random() * uuids.length)];
  const url = `${__ENV.BASE_URL}/public/card/${id}`; // adjust path as needed
  const res = http.get(url);
  check(res, {
    'status is 200': (r) => r.status === 200,
  }) || errorRate.add(1);
  sleep(1);
}
